[workspace]
resolver = "2"
members = [ "crates/kaiseki", "crates/mecab-processor", "crates/mecab-types"]

[workspace.dependencies]
mecab-types = { path = "crates/mecab-types" }

bincode = "2.0.0-rc.3"
clap = { version = "4.5.26", features = ["derive"] }
fst = "0.4.7"
