use bincode::{Decode, Encode};

#[derive(Debug, Clone, Encode, Decode)]
pub enum PartOfSpeech {
    Common,                     // 一般
    Counter,                    // 助数詞
    Noun,                       // 名詞
    AuxiliaryVerbStem,          // 助動詞語幹
    CoordinatingParticle,       // 並立助詞
    BindingParticle,            // 係助詞
    Surname,                    // 姓
    Comma,                      // 読点
    Interjection,               // 間投
    Adnominal,                  // 連体詞
    ParticleConjunction,        // 助詞類接続
    Contraction,                // 縮約
    AdjectiveConjunction,       // 形容詞接続
    AuxiliaryVerb,              // 助動詞
    QuotationString,            // 引用文字列
    Number,                     // 数
    VerbStemNonindependent,     // 動詞非自立的
    Nonindependent,             // 非自立
    Symbol,                     // 記号
    BracketClose,               // 括弧閉
    Adnominalization,           // 連体化
    Region,                     // 地域
    Adverbialization,           // 副詞化
    Alphabet,                   // アルファベット
    NumberConnection,           // 数接続
    SentenceEnd,                // 終助詞
    Suffix,                     // 接尾
    Country,                    // 国
    Other,                      // その他
    Conjunctional,              // 接続詞的
    AdjectiveStem,              // 形容動詞語幹
    Compound,                   // 連語
    ProperNoun,                 // 固有名詞
    AdverbParticle,             // 副助詞
    Adverb,                     // 副詞
    Space,                      // 空白
    Independent,                // 自立
    Verb,                       // 動詞
    VerbConnection,             // 動詞接続
    Adverbable,                 // 副詞可能
    Prefix,                     // 接頭詞
    ConjunctionParticle,        // 接続助詞
    Particle,                   // 助詞
    Name,                       // 名
    BracketOpen,                // 括弧開
    Special,                    // 特殊
    Filler,                     // フィラー
    SuruConnecting,             // サ変接続
    PersonName,                 // 人名
    Adjective,                  // 形容詞
    Pronoun,                    // 代名詞
    CaseParticle,               // 格助詞
    Exclamation,                // 感動詞
    Period,                     // 句点
    NaiAdjectiveStem,           // ナイ形容詞語幹
    Organization,               // 組織
    AdverbParticleCoordinating, // 副助詞／並立助詞／終助詞
    Quotation,                  // 引用
    Conjunction,                // 接続詞
    NounConnection,             // 名詞接続
    Unknown,
}

impl From<&str> for PartOfSpeech {
    fn from(value: &str) -> Self {
        match value {
            "一般" => Self::Common,
            "助数詞" => Self::Counter,
            "名詞" => Self::Noun,
            "助動詞語幹" => Self::AuxiliaryVerbStem,
            "並立助詞" => Self::CoordinatingParticle,
            "係助詞" => Self::BindingParticle,
            "姓" => Self::Surname,
            "読点" => Self::Comma,
            "間投" => Self::Interjection,
            "連体詞" => Self::Adnominal,
            "助詞類接続" => Self::ParticleConjunction,
            "縮約" => Self::Contraction,
            "形容詞接続" => Self::AdjectiveConjunction,
            "助動詞" => Self::AuxiliaryVerb,
            "引用文字列" => Self::QuotationString,
            "数" => Self::Number,
            "動詞非自立的" => Self::VerbStemNonindependent,
            "非自立" => Self::Nonindependent,
            "記号" => Self::Symbol,
            "括弧閉" => Self::BracketClose,
            "連体化" => Self::Adnominalization,
            "地域" => Self::Region,
            "副詞化" => Self::Adverbialization,
            "アルファベット" => Self::Alphabet,
            "数接続" => Self::NumberConnection,
            "終助詞" => Self::SentenceEnd,
            "接尾" => Self::Suffix,
            "国" => Self::Country,
            "その他" => Self::Other,
            "接続詞的" => Self::Conjunctional,
            "形容動詞語幹" => Self::AdjectiveStem,
            "連語" => Self::Compound,
            "固有名詞" => Self::ProperNoun,
            "副助詞" => Self::AdverbParticle,
            "副詞" => Self::Adverb,
            "空白" => Self::Space,
            "自立" => Self::Independent,
            "動詞" => Self::Verb,
            "動詞接続" => Self::VerbConnection,
            "副詞可能" => Self::Adverbable,
            "接頭詞" => Self::Prefix,
            "接続助詞" => Self::ConjunctionParticle,
            "助詞" => Self::Particle,
            "名" => Self::Name,
            "括弧開" => Self::BracketOpen,
            "特殊" => Self::Special,
            "フィラー" => Self::Filler,
            "サ変接続" => Self::SuruConnecting,
            "人名" => Self::PersonName,
            "形容詞" => Self::Adjective,
            "代名詞" => Self::Pronoun,
            "格助詞" => Self::CaseParticle,
            "感動詞" => Self::Interjection,
            "句点" => Self::Period,
            "ナイ形容詞語幹" => Self::NaiAdjectiveStem,
            "組織" => Self::Organization,
            "副助詞／並立助詞／終助詞" => Self::AdverbParticleCoordinating,
            "引用" => Self::Quotation,
            "接続詞" => Self::Conjunction,
            "名詞接続" => Self::NounConnection,
            _ => Self::Unknown,
        }
    }
}

impl ToString for PartOfSpeech {
    fn to_string(&self) -> String {
        match self {
            Self::Common => "一般",
            Self::Counter => "助数詞",
            Self::Noun => "名詞",
            Self::AuxiliaryVerbStem => "助動詞語幹",
            Self::CoordinatingParticle => "並立助詞",
            Self::BindingParticle => "係助詞",
            Self::Surname => "姓",
            Self::Comma => "読点",
            Self::Interjection => "間投",
            Self::Adnominal => "連体詞",
            Self::ParticleConjunction => "助詞類接続",
            Self::Contraction => "縮約",
            Self::AdjectiveConjunction => "形容詞接続",
            Self::AuxiliaryVerb => "助動詞",
            Self::QuotationString => "引用文字列",
            Self::Number => "数",
            Self::VerbStemNonindependent => "動詞非自立的",
            Self::Nonindependent => "非自立",
            Self::Symbol => "記号",
            Self::BracketClose => "括弧閉",
            Self::Adnominalization => "連体化",
            Self::Region => "地域",
            Self::Adverbialization => "副詞化",
            Self::Alphabet => "アルファベット",
            Self::NumberConnection => "数接続",
            Self::SentenceEnd => "終助詞",
            Self::Suffix => "接尾",
            Self::Country => "国",
            Self::Other => "その他",
            Self::Conjunctional => "接続詞的",
            Self::AdjectiveStem => "形容動詞語幹",
            Self::Compound => "連語",
            Self::ProperNoun => "固有名詞",
            Self::AdverbParticle => "副助詞",
            Self::Adverb => "副詞",
            Self::Space => "空白",
            Self::Independent => "自立",
            Self::Verb => "動詞",
            Self::VerbConnection => "動詞接続",
            Self::Adverbable => "副詞可能",
            Self::Prefix => "接頭詞",
            Self::ConjunctionParticle => "接続助詞",
            Self::Particle => "助詞",
            Self::Name => "名",
            Self::BracketOpen => "括弧開",
            Self::Special => "特殊",
            Self::Filler => "フィラー",
            Self::SuruConnecting => "サ変接続",
            Self::PersonName => "人名",
            Self::Adjective => "形容詞",
            Self::Pronoun => "代名詞",
            Self::CaseParticle => "格助詞",
            Self::Exclamation => "感動詞",
            Self::Period => "句点",
            Self::NaiAdjectiveStem => "ナイ形容詞語幹",
            Self::Organization => "組織",
            Self::AdverbParticleCoordinating => "副助詞／並立助詞／終助詞",
            Self::Quotation => "引用",
            Self::Conjunction => "接続詞",
            Self::NounConnection => "名詞接続",
            Self::Unknown => "未知",
        }
        .to_owned()
    }
}
