name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download mecab-ipadic
        run: bash ipadic-download.sh

      - name: Build
        run: cargo build --verbose

      - name: Generate binaries
        run: cargo run --bin mecab-processor -- --input-dir mecab --out-dir data

      - name: Test
        run: cargo test --workspace --lib --verbose

      - name: Lint
        run: cargo clippy -- -D warnings
